# Build the Rust (mmtorust) omc port instead of the bootstrapped C omc.
#
# Enabled with -DOM_OMC_ENABLE_RUST=ON. The chain, all native Rust (no bomc/omc,
# no system omc, no shell scripts):
#
#   1. cargo build the build *tools* (mmtorust, susan) -- always --release, since
#      they run during the build and release is dramatically faster.
#   2. `mmtorust susan` transpiles the Susan-subset crates; cargo builds `susan`.
#   3. `susan` compiles every *.tpl -> *.mo (the omc_add_template_target rules,
#      which use ${OMC_EXE}; in Rust mode ${OMC_EXE} is the susan binary).
#   4. `mmtorust` (full) transpiles all of compilerSources.txt -> crate .rs.
#   5. cargo builds the omc artifacts (openmodelica, libopenmodelica_compiler)
#      with a selectable profile (RUST_OMC_PROFILE, default "debug").
#
# Files are generated in their canonical locations (Compiler/Template/*.mo,
# the OpenModelica.rs crate src/ dirs); nothing is copied via scripts.

find_program(CARGO_EXECUTABLE cargo REQUIRED)

set(RUST_OMC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/OpenModelica.rs
    CACHE PATH "Path to the Rust omc source tree (the mmtorust workspace).")

# The omc artifacts (the deliverables) honour this profile; default debug.
# The build tools (mmtorust, susan) are always release regardless.
set(RUST_OMC_PROFILE "debug"
    CACHE STRING "Cargo profile for the Rust omc artifacts: debug or release.")
if(RUST_OMC_PROFILE STREQUAL "release")
  set(RUST_OMC_PROFILE_FLAG "--release")
  set(RUST_OMC_TARGET_SUBDIR "release")
else()
  set(RUST_OMC_PROFILE_FLAG "")
  set(RUST_OMC_TARGET_SUBDIR "debug")
endif()

# cargo target/ lives in the build tree, not the source crate tree.
set(RUST_OMC_TARGET_DIR ${CMAKE_CURRENT_BINARY_DIR}/rust-target
    CACHE PATH "Directory for cargo's target/ output of the Rust omc build.")
set(RUST_TARGET_DIR ${RUST_OMC_TARGET_DIR})
# Always via ${CARGO_BUILD} so target/ is never the in-source default.
set(CARGO_BUILD ${CARGO_EXECUTABLE} build --target-dir ${RUST_TARGET_DIR})
set(SUSAN_BIN   ${RUST_TARGET_DIR}/release/susan)
set(MMTORUST_BIN ${RUST_TARGET_DIR}/release/mmtorust)

# ---------------------------------------------------------------------------
# Step 1+2: build mmtorust (release), transpile the Susan subset, build susan.
# A stamp file marks completion; cargo itself handles incremental rebuilds, so
# the command always runs but is a fast no-op when nothing changed.
# ---------------------------------------------------------------------------
set(SUSAN_STAMP ${CMAKE_CURRENT_BINARY_DIR}/rust_susan.stamp)
add_custom_command(
  OUTPUT ${SUSAN_STAMP}
  WORKING_DIRECTORY ${RUST_OMC_DIR}
  # Hand make's -jN jobserver tokens to cargo (needs CMake >= 3.28).
  JOB_SERVER_AWARE TRUE
  # Build tools always in release.
  COMMAND ${CARGO_BUILD} --release -p mmtorust
  COMMAND ${MMTORUST_BIN} susan
  COMMAND ${CARGO_BUILD} --release -p openmodelica_susan --bin susan
  COMMAND ${CMAKE_COMMAND} -E touch ${SUSAN_STAMP}
  COMMENT "Rust: building mmtorust + Susan template compiler (release)"
  VERBATIM)
add_custom_target(rust_susan DEPENDS ${SUSAN_STAMP})

# In Rust mode the template rules (omc_add_template_target) invoke ${OMC_EXE} on
# each *.tpl; point it at susan and make each *.mo rule depend on rust_susan via
# TPL_EXTRA_DEPENDS (consumed by the macro).
set(OMC_EXE ${SUSAN_BIN})
set(TPL_EXTRA_DEPENDS ${SUSAN_STAMP})

# ---------------------------------------------------------------------------
# Step 4: full transpile. Depends on every template-generated *.mo
# (TPL_OUTPUT_MO_FILES, populated by template_compilation.cmake) plus the
# scripting-API .mo (generated below by the standalone scripting_api_gen tool).
# ---------------------------------------------------------------------------
function(omc_rust_setup_codegen)
  # Use the canonical CMake source list (meta_modelica_source_list.cmake), the
  # same set the C build compiles, instead of a separate hardcoded
  # compilerSources.txt — so the Rust build can never drift from it (e.g. the
  # wasm-jit files added in #15847 are picked up automatically). We materialise
  # it to a file and pass `mmtorust --sources`. Absolute paths are fine; mmtorust
  # writes its output relative to its working directory (the crate tree).
  set(RUST_SOURCES_FILE ${CMAKE_CURRENT_BINARY_DIR}/rust_compilerSources.txt)
  set(_rust_src_content "# Generated by rust_omc.cmake from meta_modelica_source_list.cmake.\n# Do not edit by hand — the canonical list is the CMake one.\n")
  foreach(_f ${OMC_MM_ALWAYS_SOURCES} ${OMC_MM_BACKEND_SOURCES})
    string(APPEND _rust_src_content "${_f}\n")
  endforeach()
  # copy_if_different so the mtime (which rust_codegen DEPENDS on) only moves on
  # a real change — a plain file(WRITE) would rewrite it every reconfigure.
  file(WRITE ${RUST_SOURCES_FILE}.tmp "${_rust_src_content}")
  execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                  ${RUST_SOURCES_FILE}.tmp ${RUST_SOURCES_FILE})

  # -------------------------------------------------------------------------
  # Generate Script/OpenModelicaScriptingAPI.mo (the typed thin wrappers around
  # the interactive API) WITHOUT a built omc, breaking the bootstrap cycle: omc
  # links libOpenModelicaCompiler.so, whose openmodelica_scripting_qt crate is
  # mmtorust-generated *from this .mo*; in the C build the .mo came from running
  # omc itself (OpenModelica.Scripting.generateScriptingAPI), which the Rust port
  # cannot do before omc exists. The standalone `scripting_api_gen` tool depends
  # only on the hand-written parser crate (openmodelica_ast, not generated), so it
  # builds and runs with no prior codegen. It parses the OpenModelica.Scripting
  # package out of FrontEnd/ModelicaBuiltin.mo and emits the .mo directly (no Tpl,
  # no Lookup). The Qt .cpp/.h are emitted later by mmtorust (emit_scripting_api_qt).
  #
  # DEPENDS on ModelicaBuiltin.mo so the API is regenerated whenever the builtin
  # OpenModelica.Scripting package changes, and on the generator's own source.
  set(SCRIPTING_API_MO ${CMAKE_CURRENT_SOURCE_DIR}/Script/OpenModelicaScriptingAPI.mo)
  set(MODELICA_BUILTIN_MO ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/ModelicaBuiltin.mo)
  add_custom_command(
    OUTPUT ${SCRIPTING_API_MO}
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    JOB_SERVER_AWARE TRUE
    COMMAND ${CARGO_BUILD} --release -p openmodelica_scripting_api_gen
    COMMAND ${RUST_TARGET_DIR}/release/scripting_api_gen ${MODELICA_BUILTIN_MO} ${SCRIPTING_API_MO}
    DEPENDS ${MODELICA_BUILTIN_MO}
            ${RUST_OMC_DIR}/openmodelica_scripting_api_gen/src/main.rs
    COMMENT "Rust: generating OpenModelicaScriptingAPI.mo from ModelicaBuiltin.mo (no omc)"
    VERBATIM)
  add_custom_target(rust_scripting_api DEPENDS ${SCRIPTING_API_MO})

  set(CODEGEN_STAMP ${CMAKE_CURRENT_BINARY_DIR}/rust_codegen.stamp)
  add_custom_command(
    OUTPUT ${CODEGEN_STAMP}
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    JOB_SERVER_AWARE TRUE
    COMMAND ${CARGO_BUILD} --release -p mmtorust
    # Strip unused `import X;` from the Susan-generated *.mo before transpiling:
    # mmtorust lowers every import to a `use crate::X`, so an unused import
    # becomes a `use` of a crate the target does not depend on (e.g.
    # `openmodelica_backend::SimCodeUtil` in openmodelica_codegen_xml). The C
    # build runs the same boot/find-unused-import.sh. It exits non-zero when it
    # removes something, so `; true` keeps the build going.
    COMMAND bash -c "\"$0\" \"$@\" ; true" ${CMAKE_CURRENT_SOURCE_DIR}/boot/find-unused-import.sh ${TPL_OUTPUT_MO_FILES}
    COMMAND ${MMTORUST_BIN} --sources ${RUST_SOURCES_FILE}
    COMMAND ${CMAKE_COMMAND} -E touch ${CODEGEN_STAMP}
    DEPENDS ${TPL_OUTPUT_MO_FILES} ${SUSAN_STAMP} ${RUST_SOURCES_FILE}
            ${CMAKE_CURRENT_SOURCE_DIR}/Script/OpenModelicaScriptingAPI.mo
    COMMENT "Rust: transpiling all MetaModelica sources (mmtorust --sources <cmake list>)"
    VERBATIM)
  add_custom_target(rust_codegen DEPENDS ${CODEGEN_STAMP})

  # -------------------------------------------------------------------------
  # Step 5: build the omc artifacts with the selected profile. Both are part of
  # `all` (ALL) so a plain `make` produces them and `make install` can stage
  # them — exactly like the C build's omc/OpenModelicaCompiler targets, which the
  # rust branch skips. rust_libopenmodelica builds the
  # target/<profile>/libOpenModelicaCompiler.so that gets installed; rust_omc
  # builds the thin launcher, which links that same .so as an external prebuilt
  # library (its build.rs finds it in the profile dir), so it must be built
  # after — hence rust_omc's DEPENDS on rust_libopenmodelica.
  # -------------------------------------------------------------------------
  add_custom_target(rust_libopenmodelica ALL
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    JOB_SERVER_AWARE TRUE
    COMMAND ${CARGO_BUILD} ${RUST_OMC_PROFILE_FLAG} -p libopenmodelica_compiler
    DEPENDS rust_codegen
    COMMENT "Rust: building libOpenModelicaCompiler (${RUST_OMC_PROFILE})"
    VERBATIM)

  add_custom_target(rust_omc ALL
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    JOB_SERVER_AWARE TRUE
    COMMAND ${CARGO_BUILD} ${RUST_OMC_PROFILE_FLAG} -p openmodelica
    DEPENDS rust_codegen rust_libopenmodelica
    COMMENT "Rust: building omc (cargo build -p openmodelica, ${RUST_OMC_PROFILE})"
    VERBATIM)

  # -------------------------------------------------------------------------
  # Install into the standard layout, mirroring the C build's install rules
  # (OMCompiler/Compiler/CMakeLists.txt, skipped in rust mode): the omc launcher
  # → bin/, the cdylib → ${CMAKE_INSTALL_LIBDIR} (lib/<triple>/omc, next to the
  # simulation-runtime libs installed by OMCompiler/SimulationRuntime under the
  # same `omc` component), and the *Builtin.mo files → lib/omc/. The launcher's
  # rpath ($ORIGIN/../lib/<triple>/omc) then resolves both the cdylib and the
  # dlopened runtime libs. Build the targets first: `make && make install`.
  # -------------------------------------------------------------------------
  set(RUST_OMC_ARTIFACT_DIR ${RUST_TARGET_DIR}/${RUST_OMC_TARGET_SUBDIR})
  install(PROGRAMS ${RUST_OMC_ARTIFACT_DIR}/openmodelica
          DESTINATION ${CMAKE_INSTALL_BINDIR} RENAME omc COMPONENT omc)
  install(PROGRAMS ${RUST_OMC_ARTIFACT_DIR}/libOpenModelicaCompiler.so
          DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT omc)
  install(FILES
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/AnnotationsBuiltin_1_x.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/AnnotationsBuiltin_2_x.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/AnnotationsBuiltin_3_x.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/NFFrontEnd/NFModelicaBuiltin.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/ModelicaBuiltin.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/MetaModelicaBuiltin.mo
            ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/PDEModelicaBuiltin.mo
          DESTINATION lib/omc COMPONENT omc)
  install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/scripts
          DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/omc/ COMPONENT omc)

  # NOTE: OpenModelicaScriptingAPI.mo is now produced by the standalone
  # scripting_api_gen tool above (rust_scripting_api target / SCRIPTING_API_MO),
  # *before* codegen, so it no longer needs a built omc and there is no bootstrap
  # cycle. The previous omc-based regeneration target has been removed.
endfunction()

# Provides, for the native CMake build of the Qt GUI clients in Rust mode, the
# OpenModelicaCompiler target they link and the OpenModelicaScriptingAPIQt sources
# OMEdit compiles — the equivalents of what the C Compiler/CMakeLists.txt (skipped
# under Rust) would define. Called whenever OM_ENABLE_GUI_CLIENTS is ON.
function(omc_rust_setup_omedit)
  set(RUST_OMC_ARTIFACT_DIR ${RUST_TARGET_DIR}/${RUST_OMC_TARGET_SUBDIR})

  # Stage the mmtorust-generated Qt scripting-API into Compiler/Script (where
  # OMEditLIB lists them as generated sources + has them on its include path), so
  # CMake's cross-dir generated-source lookup ties OMEditLib to this command and
  # OMEdit's own CMakeLists need no changes.
  set(QT_DIR ${RUST_OMC_DIR}/openmodelica_scripting_qt/qt)
  set(SCRIPT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Script)
  add_custom_command(
    OUTPUT ${SCRIPT_DIR}/OpenModelicaScriptingAPIQt.cpp
           ${SCRIPT_DIR}/OpenModelicaScriptingAPIQt.h
           ${SCRIPT_DIR}/OpenModelicaScriptingAPIQtABI.h
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
            ${QT_DIR}/OpenModelicaScriptingAPIQt.cpp
            ${QT_DIR}/OpenModelicaScriptingAPIQt.h
            ${QT_DIR}/OpenModelicaScriptingAPIQtABI.h
            ${SCRIPT_DIR}/
    DEPENDS rust_codegen rust_libopenmodelica
    COMMENT "Rust: staging OpenModelicaScriptingAPIQt.{cpp,h}+ABI into Compiler/Script for OMEdit"
    VERBATIM)
  add_custom_target(rust_omedit_api
    DEPENDS ${SCRIPT_DIR}/OpenModelicaScriptingAPIQt.cpp)

  # The OpenModelicaCompiler target the Qt GUI clients link: the cargo cdylib,
  # IMPORTED GLOBAL. IMPORTED_NO_SONAME (the cdylib has none) records the basename
  # in DT_NEEDED, resolved via the client's $ORIGIN/../lib rpath. OMC_RUST_ABI
  # selects the in-process Rust path; the include dirs provide omc_rust_embedding.h
  # and the util/ header it pulls in (SimulationRuntime/c).
  get_filename_component(_simrt_c_inc ${CMAKE_CURRENT_SOURCE_DIR}/../SimulationRuntime/c ABSOLUTE)
  add_library(OpenModelicaCompiler SHARED IMPORTED GLOBAL)
  set_target_properties(OpenModelicaCompiler PROPERTIES
    IMPORTED_LOCATION ${RUST_OMC_ARTIFACT_DIR}/libOpenModelicaCompiler.so
    IMPORTED_NO_SONAME TRUE
    INTERFACE_INCLUDE_DIRECTORIES "${RUST_OMC_DIR}/libopenmodelica_compiler/include;${_simrt_c_inc}"
    INTERFACE_COMPILE_DEFINITIONS OMC_RUST_ABI)
endfunction()
