# Build the Rust (mmtorust) omc port instead of the bootstrapped C omc.
#
# Enabled with -DOM_OMC_ENABLE_RUST=ON. The chain, all native Rust (no bomc/omc,
# no system omc, no shell scripts):
#
#   1. cargo build the build *tools* (mmtorust, susan) -- always --release, since
#      they run during the build and release is dramatically faster.
#   2. `mmtorust susan` transpiles the Susan-subset crates; cargo builds `susan`.
#   3. `susan` compiles every *.tpl -> *.mo (the omc_add_template_target rules,
#      which use ${OMC_EXE}; in Rust mode ${OMC_EXE} is the susan binary).
#   4. `mmtorust` (full) transpiles all of compilerSources.txt -> crate .rs.
#   5. cargo builds the omc artifacts (openmodelica, libopenmodelica_compiler)
#      with a selectable profile (RUST_OMC_PROFILE, default "debug").
#
# Files are generated in their canonical locations (Compiler/Template/*.mo,
# the OpenModelica.rs crate src/ dirs); nothing is copied via scripts.

find_program(CARGO_EXECUTABLE cargo REQUIRED)

set(RUST_OMC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/OpenModelica.rs
    CACHE PATH "Path to the Rust omc source tree (the mmtorust workspace).")

# The omc artifacts (the deliverables) honour this profile; default debug.
# The build tools (mmtorust, susan) are always release regardless.
set(RUST_OMC_PROFILE "debug"
    CACHE STRING "Cargo profile for the Rust omc artifacts: debug or release.")
if(RUST_OMC_PROFILE STREQUAL "release")
  set(RUST_OMC_PROFILE_FLAG "--release")
  set(RUST_OMC_TARGET_SUBDIR "release")
else()
  set(RUST_OMC_PROFILE_FLAG "")
  set(RUST_OMC_TARGET_SUBDIR "debug")
endif()

set(RUST_TARGET_DIR ${RUST_OMC_DIR}/target)
set(SUSAN_BIN   ${RUST_TARGET_DIR}/release/susan)
set(MMTORUST_BIN ${RUST_TARGET_DIR}/release/mmtorust)

# ---------------------------------------------------------------------------
# Step 1+2: build mmtorust (release), transpile the Susan subset, build susan.
# A stamp file marks completion; cargo itself handles incremental rebuilds, so
# the command always runs but is a fast no-op when nothing changed.
# ---------------------------------------------------------------------------
set(SUSAN_STAMP ${CMAKE_CURRENT_BINARY_DIR}/rust_susan.stamp)
add_custom_command(
  OUTPUT ${SUSAN_STAMP}
  WORKING_DIRECTORY ${RUST_OMC_DIR}
  # Build tools always in release.
  COMMAND ${CARGO_EXECUTABLE} build --release -p mmtorust
  COMMAND ${MMTORUST_BIN} susan
  COMMAND ${CARGO_EXECUTABLE} build --release -p openmodelica_susan --bin susan
  COMMAND ${CMAKE_COMMAND} -E touch ${SUSAN_STAMP}
  COMMENT "Rust: building mmtorust + Susan template compiler (release)"
  VERBATIM)
add_custom_target(rust_susan DEPENDS ${SUSAN_STAMP})

# In Rust mode the template rules (omc_add_template_target) invoke ${OMC_EXE} on
# each *.tpl; point it at susan and make each *.mo rule depend on rust_susan via
# TPL_EXTRA_DEPENDS (consumed by the macro).
set(OMC_EXE ${SUSAN_BIN})
set(TPL_EXTRA_DEPENDS ${SUSAN_STAMP})

# ---------------------------------------------------------------------------
# Step 4: full transpile. Depends on every template-generated *.mo
# (TPL_OUTPUT_MO_FILES, populated by template_compilation.cmake) plus the
# scripting-API .mo (generated below by the standalone scripting_api_gen tool).
# ---------------------------------------------------------------------------
function(omc_rust_setup_codegen)
  # Use the canonical CMake source list (meta_modelica_source_list.cmake), the
  # same set the C build compiles, instead of a separate hardcoded
  # compilerSources.txt — so the Rust build can never drift from it (e.g. the
  # wasm-jit files added in #15847 are picked up automatically). We materialise
  # it to a file and pass `mmtorust --sources`. Absolute paths are fine; mmtorust
  # writes its output relative to its working directory (the crate tree).
  set(RUST_SOURCES_FILE ${CMAKE_CURRENT_BINARY_DIR}/rust_compilerSources.txt)
  set(_rust_src_content "# Generated by rust_omc.cmake from meta_modelica_source_list.cmake.\n# Do not edit by hand — the canonical list is the CMake one.\n")
  foreach(_f ${OMC_MM_ALWAYS_SOURCES} ${OMC_MM_BACKEND_SOURCES})
    string(APPEND _rust_src_content "${_f}\n")
  endforeach()
  file(WRITE ${RUST_SOURCES_FILE} "${_rust_src_content}")

  # -------------------------------------------------------------------------
  # Generate Script/OpenModelicaScriptingAPI.mo (the typed thin wrappers around
  # the interactive API) WITHOUT a built omc, breaking the bootstrap cycle: omc
  # links libOpenModelicaCompiler.so, whose openmodelica_scripting_qt crate is
  # mmtorust-generated *from this .mo*; in the C build the .mo came from running
  # omc itself (OpenModelica.Scripting.generateScriptingAPI), which the Rust port
  # cannot do before omc exists. The standalone `scripting_api_gen` tool depends
  # only on the hand-written parser crate (openmodelica_ast, not generated), so it
  # builds and runs with no prior codegen. It parses the OpenModelica.Scripting
  # package out of FrontEnd/ModelicaBuiltin.mo and emits the .mo directly (no Tpl,
  # no Lookup). The Qt .cpp/.h are emitted later by mmtorust (emit_scripting_api_qt).
  #
  # DEPENDS on ModelicaBuiltin.mo so the API is regenerated whenever the builtin
  # OpenModelica.Scripting package changes, and on the generator's own source.
  set(SCRIPTING_API_MO ${CMAKE_CURRENT_SOURCE_DIR}/Script/OpenModelicaScriptingAPI.mo)
  set(MODELICA_BUILTIN_MO ${CMAKE_CURRENT_SOURCE_DIR}/FrontEnd/ModelicaBuiltin.mo)
  add_custom_command(
    OUTPUT ${SCRIPTING_API_MO}
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    COMMAND ${CARGO_EXECUTABLE} build --release -p openmodelica_scripting_api_gen
    COMMAND ${RUST_TARGET_DIR}/release/scripting_api_gen ${MODELICA_BUILTIN_MO} ${SCRIPTING_API_MO}
    DEPENDS ${MODELICA_BUILTIN_MO}
            ${RUST_OMC_DIR}/openmodelica_scripting_api_gen/src/main.rs
    COMMENT "Rust: generating OpenModelicaScriptingAPI.mo from ModelicaBuiltin.mo (no omc)"
    VERBATIM)
  add_custom_target(rust_scripting_api DEPENDS ${SCRIPTING_API_MO})

  set(CODEGEN_STAMP ${CMAKE_CURRENT_BINARY_DIR}/rust_codegen.stamp)
  add_custom_command(
    OUTPUT ${CODEGEN_STAMP}
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    COMMAND ${CARGO_EXECUTABLE} build --release -p mmtorust
    # Strip unused `import X;` from the Susan-generated *.mo before transpiling:
    # mmtorust lowers every import to a `use crate::X`, so an unused import
    # becomes a `use` of a crate the target does not depend on (e.g.
    # `openmodelica_backend::SimCodeUtil` in openmodelica_codegen_xml). The C
    # build runs the same boot/find-unused-import.sh. It exits non-zero when it
    # removes something, so `; true` keeps the build going.
    COMMAND bash -c "\"$0\" \"$@\" ; true" ${CMAKE_CURRENT_SOURCE_DIR}/boot/find-unused-import.sh ${TPL_OUTPUT_MO_FILES}
    COMMAND ${MMTORUST_BIN} --sources ${RUST_SOURCES_FILE}
    COMMAND ${CMAKE_COMMAND} -E touch ${CODEGEN_STAMP}
    DEPENDS ${TPL_OUTPUT_MO_FILES} ${SUSAN_STAMP} ${RUST_SOURCES_FILE}
            ${CMAKE_CURRENT_SOURCE_DIR}/Script/OpenModelicaScriptingAPI.mo
    COMMENT "Rust: transpiling all MetaModelica sources (mmtorust --sources <cmake list>)"
    VERBATIM)
  add_custom_target(rust_codegen DEPENDS ${CODEGEN_STAMP})

  # -------------------------------------------------------------------------
  # Step 5: build the omc artifacts with the selected profile.
  # -------------------------------------------------------------------------
  add_custom_target(rust_omc
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    COMMAND ${CARGO_EXECUTABLE} build ${RUST_OMC_PROFILE_FLAG} -p openmodelica
    DEPENDS rust_codegen
    COMMENT "Rust: building omc (cargo build -p openmodelica, ${RUST_OMC_PROFILE})"
    VERBATIM)

  add_custom_target(rust_libopenmodelica
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    COMMAND ${CARGO_EXECUTABLE} build ${RUST_OMC_PROFILE_FLAG} -p libopenmodelica_compiler
    DEPENDS rust_codegen
    COMMENT "Rust: building libOpenModelicaCompiler (${RUST_OMC_PROFILE})"
    VERBATIM)
  # NOTE: OpenModelicaScriptingAPI.mo is now produced by the standalone
  # scripting_api_gen tool above (rust_scripting_api target / SCRIPTING_API_MO),
  # *before* codegen, so it no longer needs a built omc and there is no bootstrap
  # cycle. The previous omc-based regeneration target has been removed.
endfunction()

# OMEdit built in-process against the Rust libOpenModelicaCompiler.so. This is
# the CMake reimplementation of build-omedit.sh's steps (the script is no longer
# the build mechanism): build the cdylib, install the Rust scripting-API
# interface + embedding headers and the .so into the build tree's canonical
# locations, then build OMPlot + OMEdit with the upstream `CONFIG+=rust_omc`
# switch (#15848). Driven by cache vars so it works outside the default layout.
# Enable with -DOM_OMC_ENABLE_RUST_OMEDIT=ON.
function(omc_rust_setup_omedit)
  set(OM_BUILD_DIR ${CMAKE_BINARY_DIR} CACHE PATH "OpenModelica build tree (bin/, lib/, include/).")
  set(OMEDIT_DIR ${CMAKE_SOURCE_DIR}/../OMEdit CACHE PATH "OMEdit source tree (the .pro lives here).")
  find_program(QMAKE_EXECUTABLE NAMES qmake6 qmake REQUIRED)
  execute_process(COMMAND gcc -dumpmachine OUTPUT_VARIABLE HOST_TRIPLE OUTPUT_STRIP_TRAILING_WHITESPACE)
  set(OMC_LIB_DIR ${OM_BUILD_DIR}/lib/${HOST_TRIPLE}/omc)
  set(OMC_API_INC ${OM_BUILD_DIR}/include/omc/scripting-API)
  set(QT_DIR ${RUST_OMC_DIR}/openmodelica_scripting_qt/qt)

  add_custom_target(rust_omedit
    COMMENT "Rust: building OMEdit against libOpenModelicaCompiler (CONFIG+=rust_omc)"
    # 1. the cdylib (release recommended for OMEdit).
    COMMAND ${CARGO_EXECUTABLE} build ${RUST_OMC_PROFILE_FLAG} -p libopenmodelica_compiler
    # 2. install the .so + the Rust scripting-API interface/embedding headers
    #    into the build tree where OMEdit's rpath ($ORIGIN/../lib) finds them.
    COMMAND ${CMAKE_COMMAND} -E make_directory ${OMC_LIB_DIR} ${OMC_API_INC}
    COMMAND ${CMAKE_COMMAND} -E copy
            ${RUST_TARGET_DIR}/${RUST_OMC_TARGET_SUBDIR}/libOpenModelicaCompiler.so ${OMC_LIB_DIR}/
    COMMAND ${CMAKE_COMMAND} -E copy
            ${QT_DIR}/OpenModelicaScriptingAPIQt.cpp ${QT_DIR}/OpenModelicaScriptingAPIQt.h
            ${QT_DIR}/OpenModelicaScriptingAPIQtABI.h
            ${RUST_OMC_DIR}/libopenmodelica_compiler/include/omc_rust_embedding.h ${OMC_API_INC}/
    # 3. qmake + make OMEdit with the rust_omc switch (#15848).
    COMMAND ${CMAKE_COMMAND} -E chdir ${OMEDIT_DIR} ${QMAKE_EXECUTABLE} -r CONFIG+=rust_omc
    COMMAND ${CMAKE_COMMAND} -E chdir ${OMEDIT_DIR} make -j
    WORKING_DIRECTORY ${RUST_OMC_DIR}
    DEPENDS rust_libopenmodelica
    VERBATIM)
endfunction()
